count: 1000
snr: 50
add_noise: True

dm_range:
  lower_dm_value: 0.0
  upper_dm_value: 0.3

scattering_measure:
  sm_lower: 0.0
  sm_upper: 1.0

drift_rates:
  lo: -1
  up: -20
  
component_0:
  arrival_time: 3.0

  width: 
    width_lower_value: 0.0001
    width_upper_value: 0.01

  fluence:
    fluence_lower_value: 5.0
    fluence_upper_value: 50.0

  spectral_index:
    spec_lower_value: 0.0
    spec_upper_value: 0.0

  spectral_running: 
    sr_lower_value: 0.0
    sr_upper_value: 0.0 

cent_freq:
  lo: 425 
  up: 775

bandwidth: 
  lo: 100
  up: 200  
arr_time_sep:
  lo: 0.003
  hi: 0.010
