count: 1000
snr: 50
add_noise: True
peaks: 1

dm_range:
  lower_dm_value: 0.0
  upper_dm_value: 1.0 

scattering_measure:
  sm_lower: 0.0
  sm_upper: 3.5
theta:
  min: 2.0
  max: 40.0

component_0:
  arrival_time: 3.0

  width: 
    width_lower_value: 0.001
    width_upper_value: 0.030

  fluence:
    fluence_lower_value: 5.0
    fluence_upper_value: 50.0

  spectral_index :
    spec_lower_value: -3.0
    spec_upper_value: 3.0

  spectral_running: 
    sr_lower_value: 0.0
    sr_upper_value: 0.0 


