count: 1000
snr: 50
add_noise: True

dm_range:
  lower_dm_value: 0.0
  upper_dm_value: 0.3 

scattering_measure:
  sm_lower: 0.0
  sm_upper: 2.0


component_0:
  arrival_time: 3.0

  width: 
    width_lower_value: 0.005
    width_upper_value: 0.025

  fluence:
    fluence_lower_value: 5.0
    fluence_upper_value: 50.0

  spectral_index:
    spec_lower_value: 0
    spec_upper_value: 0

  spectral_running: 
    sr_lower_value: 0.0
    sr_upper_value: 0.0 


